
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * List.java
 *
 * Created on Nov 18, 2010, 2:06:58 PM
 */

/**
 *
 * @author user
 */
public class List extends javax.swing.JFrame {
String subject="";
int no;
int mark;
    /** Creates new form List */
    public List() {
        initComponents();
    }
    public List(int marks) {
        initComponents();
        mark=marks;
    }

 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listbtngrp = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        listbtngrp.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("PHYSICS");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        listbtngrp.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("JAVA");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        listbtngrp.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("CHEMISTRY");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        listbtngrp.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("MATHS");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("SELECT AN OPTION :-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, -1));

        jButton1.setBackground(new java.awt.Color(102, 0, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Select ");
        jButton1.setToolTipText("Click To Open Question Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\DPS23\\My Documents\\Downloads\\6.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select

        if(jRadioButton1.isSelected())
        {
            subject = "physics";
            no=1;
        }
        if(jRadioButton2.isSelected())
        {
    
            subject ="java";
            no=6;
        }
        if(jRadioButton3.isSelected())
        {
           
            subject= "Chemistry";
            no=11;
        }
        if(jRadioButton4.isSelected())
        {
         
            subject = "maths";
            no=16;
        }
        {
            if (subject != "")
        {
           question r = new question(subject,no,mark);
           r.setVisible(true);
           this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Please Choose A subject");
        }
        }
    }//GEN-LAST:event_select

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.ButtonGroup listbtngrp;
    // End of variables declaration//GEN-END:variables

}
